export const HORSE_BREEDS = [
  'Achałtekińska',
  'American Paint Horse',
  'Andaluzyjska',
  'Ane Grand Noir du Berry',
  'Appaloosa',
  'Arden francuski',
  'Arden polski',
  'Arden szwedzki',
  'Ardenofiord',
  'Ardeńska',
  'Austriacki koń gorącokrwisty',
  'Baudet Poitou',
  'Bawarska',
  'Beberbecka',
  'Belgijska',
  'Berberyjska',
  'Brandenburska',
  'Bretońska',
  'Budionowska',
  'Bulońska',
  'Cheval de selle',
  'Clydesdale',
  'Cob normandzki',
  'Comtois',
  'Czeska',
  'Duńska',
  'Europees Stamboek',
  'Fallabella',
  'Fiordzka',
  'Francuski kuc wierzchowy',
  'Freiberger',
  'Fryderyksborska',
  'Fryzyjska',
  'Furioso',
  'Gudbrandsdalska',
  'Gypsy cob',
  'Hackney',
  'Haflinger',
  'Hanowerska',
  'Heska',
  'Holsztyńska',
  'Huculska',
  'Irish Cob',
  'Irlandzki koń sportowy',
  'Kabardyńska',
  'Katalońska',
  'Kazachska',
  'Kladrubska',
  'Kłusak',
  'Konik biłgorajski',
  'Konik polski',
  'Koń anglo-doński',
  'Koń anglo-normandzki',
  'Koń arabski',
  'Koń arabski chowany w czystości krwi',
  'Koń doński',
  'Koń graditzki',
  'Koń Jutlandzki',
  'Koń lidzbarski',
  'Koń mazurski',
  'Koń norycki',
  'Koń pinto',
  'Koń pomorski',
  'Koń poznański',
  'Koń Przewalskiego',
  'Koń sokólski',
  'Koń sztumski',
  'Koń trakeński',
  'Koń wschodniopruski',
  'Księga stadna Zangersheide',
  'Kuc angielski',
  'Kuc connemara',
  'Kuc dartmoor',
  'Kuc exmoor',
  'Kuc Feliński',
  'Kuc Fell',
  'Kuc highland',
  'Kuc islandzki',
  'Kuc Lewitzer',
  'Kuc new forest',
  'Kuc niemiecki',
  'Kuc szetlandzki',
  'Kuc walijski',
  'Kuc wierzchowy',
  'Kustyjska',
  'KWPN',
  'LA SILLA',
  'Le cheval de sport Belge',
  'Lewitzer',
  'Lipicańska',
  'Litewska',
  'Luksemburska gorącokrwista',
  'Lusitano',
  'Łotewska',
  'Łotewska',
  'Małopolska',
  'Maremmano',
  'Meckenburska',
  'Missouri Fox Trotter',
  'Morgan',
  'Mur insulan',
  'Nederlandse Appaloosa Stamboek',
  'Niemiecka wierzchowa',
  'Niemiecki koń sportowy',
  'NWP',
  'Oldenburska',
  'Oryginalny arab',
  'Pełna krew angielska',
  'Perszeron',
  'Polski koń szlachetny półkrwi',
  'Polski koń zimnokrwisty',
  'Polski kuc szetlandzki',
  'Półkrew angielska',
  'Półkrew angloarabska',
  'Półkrew arabska',
  'Północno-szwedzka',
  'Pura Raza Espanola',
  'Quarter horse',
  'Reńska',
  'Saksońska',
  'Schweres warmblud',
  'Selle francais',
  'Shagya',
  'Shire',
  'Słowacki koń gorącokrwisty',
  'Szwajcarska',
  'Szwedzka',
  'Śląska',
  'Tennessee Walking Horse',
  'Tierska',
  'Tinker',
  'Toryjska',
  'Trakeńska',
  'Turyngijska',
  'Typ koń mały',
  'Typ kuc',
  'Typ pogrubiony',
  'Typ prymitywny',
  'Typ szlachetny',
  'Typ zimnokrwisty',
  'Ukraińska',
  'Warmblutschecke',
  'Westfalska',
  'Węgierska półkrew',
  'Wielkopolska',
  'Wirtemberska',
  'Włoska wierzchowa',
  'Wschodniofryzyjska',
  'Žemaitukai',
  'Zimnokrwista',
  'Zweibrücker',
  'Rasa nieznana',
] as const
